import {
  Category,
  Product,
  User,
  DeliveryEmployee,
  RestaurantSettings,
  WhatsAppTemplate,
  InventoryItem,
  Expense,
  Customer,
  Order,
} from '../src/types';

export const initialCategories: Category[] = [
  {
    id: 'cat-broast',
    nameAr: 'وجبات البروست والمقلي',
    nameEn: 'Broast & Strips Meals',
    icon: 'kebab_dining',
    sortOrder: 1,
  },
  {
    id: 'cat-burgers',
    nameAr: 'برجر لحم مشوي على النار',
    nameEn: 'Charcoal Grilled Beef Burgers',
    icon: 'lunch_dining',
    sortOrder: 2,
  },
  {
    id: 'cat-tacos',
    nameAr: 'ساندوتشات التاكو والدجاج',
    nameEn: 'Taco & Chicken Sandwiches',
    icon: 'tapas',
    sortOrder: 3,
  },
  {
    id: 'cat-sides',
    nameAr: 'المقبلات والبطاطس',
    nameEn: 'Sides & Fries',
    icon: 'fastfood',
    sortOrder: 4,
  },
  {
    id: 'cat-sauces',
    nameAr: 'صوصات تاكو بروست',
    nameEn: 'Taco Broast Sauces',
    icon: 'liquor',
    sortOrder: 5,
  },
  {
    id: 'cat-drinks',
    nameAr: 'المشروبات الغازية والمياه',
    nameEn: 'Beverages & Drinks',
    icon: 'local_cafe',
    sortOrder: 6,
  },
];

export const initialProducts: Product[] = [
  // --- وجبات البروست والمقلي ---
  {
    id: 'prod-b1',
    sku: 'TB-B01',
    barcode: '62210001',
    nameAr: 'وجبة 2 قطع',
    nameEn: 'Meal 2 Pcs',
    descriptionAr: '2 قطع زنجر أو كريسبي ستربس مقرمش + خبز كيزر + كاتشب + بطاطس مقلية + صوص تومية مميز',
    descriptionEn: '2 Pcs crispy zinger/strips + bun + ketchup + fries + special garlic dip',
    price: 75,
    costPrice: 42,
    categoryId: 'cat-broast',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isPopular: true,
    hasSpicyOption: true,
    extras: [
      { id: 'ex-fries', nameAr: 'بطاطس إضافية', nameEn: 'Extra Fries', price: 15, isAvailable: true },
      { id: 'ex-cheddar', nameAr: 'صوص شيدر إضافي', nameEn: 'Extra Cheddar', price: 15, isAvailable: true },
      { id: 'ex-garlic', nameAr: 'تومية إضافية', nameEn: 'Extra Garlic Dip', price: 10, isAvailable: true },
      { id: 'ex-mozz', nameAr: 'وش موتزاريلا سايحة', nameEn: 'Melted Mozzarella', price: 20, isAvailable: true },
    ],
  },
  {
    id: 'prod-b2',
    sku: 'TB-B02',
    barcode: '62210002',
    nameAr: 'وجبة 3 قطع',
    nameEn: 'Meal 3 Pcs',
    descriptionAr: '3 قطع زنجر أو كريسبي ستربس متبل بخلطة سرية + تومية + خبز + كاتشب + بطاطس مقلية ذهبية',
    descriptionEn: '3 Pcs seasoned crispy chicken + garlic dip + bun + ketchup + golden fries',
    price: 105,
    costPrice: 58,
    categoryId: 'cat-broast',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isPopular: true,
    hasSpicyOption: true,
    extras: [
      { id: 'ex-fries', nameAr: 'بطاطس إضافية', nameEn: 'Extra Fries', price: 15, isAvailable: true },
      { id: 'ex-cheddar', nameAr: 'صوص شيدر إضافي', nameEn: 'Extra Cheddar', price: 15, isAvailable: true },
      { id: 'ex-coleslaw', nameAr: 'كول سلو غني', nameEn: 'Rich Coleslaw', price: 10, isAvailable: true },
    ],
  },
  {
    id: 'prod-b3',
    sku: 'TB-B03',
    barcode: '62210003',
    nameAr: 'وجبة 4 قطع',
    nameEn: 'Meal 4 Pcs',
    descriptionAr: '4 قطع دجاج زنجر أو ستربس فائق القرمشة + تومية + خبز + كاتشب + باكت بطاطس',
    descriptionEn: '4 Pcs super crispy chicken + garlic dip + bun + ketchup + packet fries',
    price: 140,
    costPrice: 78,
    categoryId: 'cat-broast',
    image: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    hasSpicyOption: true,
  },
  {
    id: 'prod-b4',
    sku: 'TB-B04',
    barcode: '62210004',
    nameAr: 'وجبة 5 قطع',
    nameEn: 'Meal 5 Pcs',
    descriptionAr: '5 قطع دجاج مقرمش شهي + خبز + كاتشب + بطاطس مقلية + سلطة كول سلو بالكريمة الغنية',
    descriptionEn: '5 Pcs delicious crispy chicken + bun + ketchup + fries + creamy coleslaw',
    price: 170,
    costPrice: 94,
    categoryId: 'cat-broast',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    hasSpicyOption: true,
  },
  {
    id: 'prod-b5',
    sku: 'TB-B05',
    barcode: '62210005',
    nameAr: 'وجبة 6 قطع سوبر',
    nameEn: 'Meal 6 Pcs Super',
    descriptionAr: '6 قطع دجاج بروست أو ستربس + صوص تومية + خبز + كاتشب + باكت بطاطس + كول سلو',
    descriptionEn: '6 Pcs broast chicken or strips + garlic sauce + bun + ketchup + fries + coleslaw',
    price: 190,
    costPrice: 105,
    categoryId: 'cat-broast',
    image: 'https://images.unsplash.com/photo-1513639776629-7b61b0ac49cb?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    hasSpicyOption: true,
  },
  {
    id: 'prod-b6',
    sku: 'TB-B06',
    barcode: '62210006',
    nameAr: 'وجبة 10 قطع عائلية',
    nameEn: 'Family Meal 10 Pcs',
    descriptionAr: '10 قطع دجاج ستربس أو بروست عائلي + علبة تومية كبيرة + 3 خبز + كاتشب + بطاطس لارج + كول سلو',
    descriptionEn: '10 Pcs family chicken + large garlic dip + 3 buns + ketchup + large fries + coleslaw',
    price: 330,
    costPrice: 185,
    categoryId: 'cat-broast',
    image: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isPopular: true,
    hasSpicyOption: true,
  },
  {
    id: 'prod-b7',
    sku: 'TB-B07',
    barcode: '62210007',
    nameAr: 'وجبة 15 قطعة بارتي',
    nameEn: 'Party Meal 15 Pcs',
    descriptionAr: '15 قطعة دجاج كريسبي مقرمش + 2 تومية كبير + 5 خبز طازج + 2 بطاطس لارج + 2 كول سلو كبير',
    descriptionEn: '15 Pcs party crispy chicken + 2 large garlic dips + 5 fresh buns + 2 large fries + 2 coleslaws',
    price: 460,
    costPrice: 255,
    categoryId: 'cat-broast',
    image: 'https://images.unsplash.com/photo-1513639776629-7b61b0ac49cb?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    hasSpicyOption: true,
  },
  {
    id: 'prod-b8',
    sku: 'TB-B08',
    barcode: '62210008',
    nameAr: 'وجبة 20 قطعة سوبر جامبو',
    nameEn: 'Super Jumbo 20 Pcs',
    descriptionAr: '20 قطعة دجاج متبلة بالخلطة الأصلية + 3 تومية لارج + 6 كيس عيش + 3 باكت بطاطس كبير + 3 كول سلو',
    descriptionEn: '20 Pcs super jumbo original chicken + 3 large garlic dips + 6 buns + 3 large fries + 3 coleslaw',
    price: 585,
    costPrice: 320,
    categoryId: 'cat-broast',
    image: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    hasSpicyOption: true,
  },

  // --- برجر لحم مشوي على النار ---
  {
    id: 'prod-br1',
    sku: 'TB-BR01',
    barcode: '62220001',
    nameAr: 'تكساس برجر',
    nameEn: 'Texas Burger',
    descriptionAr: 'لحم بقري صافي مشوي على النار بنكهة الشواء الحقيقية + صوص تكساس + بيف بيكون + صوص الشيدر + مايونيز + خس طازج',
    descriptionEn: 'Flame-grilled pure beef + Texas BBQ sauce + beef bacon + cheddar sauce + mayo + fresh lettuce',
    price: 95,
    costPrice: 52,
    categoryId: 'cat-burgers',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isPopular: true,
    extras: [
      { id: 'ex-patty', nameAr: 'قطعة برجر إضافية', nameEn: 'Extra Beef Patty', price: 40, isAvailable: true },
      { id: 'ex-cheddar', nameAr: 'جبنة شيدر إضافية', nameEn: 'Extra Cheddar', price: 15, isAvailable: true },
      { id: 'ex-jalapeno', nameAr: 'هالبينو مكسيكي حار', nameEn: 'Spicy Jalapeno', price: 10, isAvailable: true },
      { id: 'ex-bacon', nameAr: 'بيف بيكون مقرمش', nameEn: 'Crispy Beef Bacon', price: 20, isAvailable: true },
    ],
  },
  {
    id: 'prod-br2',
    sku: 'TB-BR02',
    barcode: '62220002',
    nameAr: 'سويت برجر',
    nameEn: 'Sweet Burger',
    descriptionAr: 'لحم بقري مشوي + بصل مكرمل مدخن + فلفل مشوي على اللهب + صوص سويت + صوص الشيدر + مايونيز وخس',
    descriptionEn: 'Grilled beef + smoked caramelized onions + flame grilled peppers + sweet sauce + cheddar + mayo & lettuce',
    price: 109,
    costPrice: 60,
    categoryId: 'cat-burgers',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-br3',
    sku: 'TB-BR03',
    barcode: '62220003',
    nameAr: 'فادج برجر لمحبي الجبن',
    nameEn: 'Fudge Cheese Lovers Burger',
    descriptionAr: 'لحم بقري فاخر مغرق بجبنة موتزاريلا سايحة + شلال صوص الشيدر السائب + مايونيز وخس مقرمش',
    descriptionEn: 'Premium beef flooded in melted mozzarella + waterfall of cheddar sauce + mayo + crisp lettuce',
    price: 109,
    costPrice: 62,
    categoryId: 'cat-burgers',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'prod-br4',
    sku: 'TB-BR04',
    barcode: '62220004',
    nameAr: 'أمريكان بيف',
    nameEn: 'American Beef',
    descriptionAr: 'لحم بقري صافي + بيف بيكون + صوص أمريكان السري + صوص الشيدر الغني + مايونيز وخس طازج',
    descriptionEn: 'Pure beef + beef bacon + secret American sauce + rich cheddar + mayo + fresh lettuce',
    price: 99,
    costPrice: 55,
    categoryId: 'cat-burgers',
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-br5',
    sku: 'TB-BR05',
    barcode: '62220005',
    nameAr: 'تشيزي بايتس',
    nameEn: 'Cheesy Bites Burger',
    descriptionAr: 'لحم بقري مشوي + صوابع الجبنة الموتزاريلا المقرمشة بقلب الساندوتش + صوص الشيدر + مايونيز وخس',
    descriptionEn: 'Grilled beef + crunchy mozzarella cheese sticks tucked inside + cheddar sauce + mayo & lettuce',
    price: 109,
    costPrice: 61,
    categoryId: 'cat-burgers',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isNewArrival: true,
  },
  {
    id: 'prod-br6',
    sku: 'TB-BR06',
    barcode: '62220006',
    nameAr: 'دوبل برجر لحم',
    nameEn: 'Double Beef Burger',
    descriptionAr: '2 قطعة لحم بقري صافي مشوي + صوص تكساس + بيف بيكون + صوص الشيدر السايح + مايونيز وخس',
    descriptionEn: '2 flame grilled beef patties + Texas sauce + beef bacon + melted cheddar + mayo & lettuce',
    price: 160,
    costPrice: 88,
    categoryId: 'cat-burgers',
    image: 'https://images.unsplash.com/photo-1583032015879-66c3c5ee9655?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'prod-br7',
    sku: 'TB-BR07',
    barcode: '62220007',
    nameAr: 'تريبل برجر عملاق',
    nameEn: 'Triple Beef Burger Giant',
    descriptionAr: '3 قطع لحم بقري صافي مشوي على النار + بيف بيكون + صوص تكساس مضاعف + شيدر مضاعف + مايونيز وخس',
    descriptionEn: '3 grilled beef patties + double beef bacon + double Texas sauce + double cheddar + mayo & lettuce',
    price: 190,
    costPrice: 106,
    categoryId: 'cat-burgers',
    image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },

  // --- ساندوتشات التاكو والدجاج ---
  {
    id: 'prod-tc1',
    sku: 'TB-TC01',
    barcode: '62230001',
    nameAr: 'تاكو كلاسيك',
    nameEn: 'Classic Taco',
    descriptionAr: '1 قطعة سكالوب دجاج متبل + صوص الشيدر + خس طازج + صوص تاكو بروست الخاص',
    descriptionEn: '1 seasoned chicken escalope + cheddar sauce + fresh lettuce + signature Taco Broast sauce',
    price: 80,
    costPrice: 44,
    categoryId: 'cat-tacos',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isPopular: true,
    hasSpicyOption: true,
  },
  {
    id: 'prod-tc2',
    sku: 'TB-TC02',
    barcode: '62230002',
    nameAr: 'تركي تاكو',
    nameEn: 'Turkey Taco',
    descriptionAr: '1 قطعة سكالوب دجاج + تركي مدخن فاخر + صوص الشيدر + صوص تاكو بروست + خس طازج',
    descriptionEn: '1 chicken escalope + premium smoked turkey + cheddar sauce + Taco Broast sauce + lettuce',
    price: 85,
    costPrice: 47,
    categoryId: 'cat-tacos',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    hasSpicyOption: true,
  },
  {
    id: 'prod-tc3',
    sku: 'TB-TC03',
    barcode: '62230003',
    nameAr: 'سوبريم تاكو بروست',
    nameEn: 'Supreme Taco Broast',
    descriptionAr: '2 قطعة زنجر أو ستربس + وش جبنة موتزاريلا سايحة + رومي مدخن + صوص الشيدر + صوص تاكو بروست + مايونيز وخس',
    descriptionEn: '2 zinger/strips pieces + melted mozzarella layer + smoked turkey + cheddar + Taco sauce + mayo & lettuce',
    price: 90,
    costPrice: 50,
    categoryId: 'cat-tacos',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isPopular: true,
    hasSpicyOption: true,
  },
  {
    id: 'prod-tc4',
    sku: 'TB-TC04',
    barcode: '62230004',
    nameAr: 'تويستر تشيكن',
    nameEn: 'Twister Chicken',
    descriptionAr: '2 قطعة زنجر أو ستربس + رومي مدخن + صوص الشيدر + مخلل خيار + صوص تاكو بروست + خس طازج',
    descriptionEn: '2 zinger/strips pieces + smoked turkey + cheddar + pickles + Taco sauce + fresh lettuce',
    price: 80,
    costPrice: 44,
    categoryId: 'cat-tacos',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    hasSpicyOption: true,
  },
  {
    id: 'prod-tc5',
    sku: 'TB-TC05',
    barcode: '62230005',
    nameAr: 'راب تشيكن',
    nameEn: 'Chicken Wrap',
    descriptionAr: '2 قطعة زنجر أو ستربس + جبنة موتزاريلا سايحة + صوص الشيدر + صوص تاكو بروست داخل خبز التورتيلا المميز',
    descriptionEn: '2 zinger/strips pieces + melted mozzarella + cheddar sauce + Taco Broast sauce wrapped in tortilla',
    price: 90,
    costPrice: 50,
    categoryId: 'cat-tacos',
    image: 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    hasSpicyOption: true,
  },
  {
    id: 'prod-tc6',
    sku: 'TB-TC06',
    barcode: '62230006',
    nameAr: 'تاكو تشيزي موتزاريلا',
    nameEn: 'Mozzarella Cheesy Taco',
    descriptionAr: '1 قطعة بانيه مقرمش + موتزاريلا ستيكس مقرمشة + صوص الشيدر + خس طازج',
    descriptionEn: '1 crispy pane piece + crunchy mozzarella sticks + cheddar sauce + fresh lettuce',
    price: 90,
    costPrice: 49,
    categoryId: 'cat-tacos',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-tc7',
    sku: 'TB-TC07',
    barcode: '62230007',
    nameAr: 'ساندوتش ستربس',
    nameEn: 'Strips Sandwich',
    descriptionAr: '2 قطعة ستربس دجاج + رومي مدخن + صوص الشيدر + صوص تاكو بروست + مخلل وخس',
    descriptionEn: '2 chicken strips + smoked turkey + cheddar sauce + Taco sauce + pickles & lettuce',
    price: 80,
    costPrice: 43,
    categoryId: 'cat-tacos',
    image: 'https://images.unsplash.com/photo-1606755962773-d324e0a13086?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-tc8',
    sku: 'TB-TC08',
    barcode: '62230008',
    nameAr: 'تاكو زنجر حار',
    nameEn: 'Spicy Zinger Taco',
    descriptionAr: '2 قطعة زنجر مقرمش سبايسي + رومي مدخن + صوص الشيدر + صوص تاكو بروست + مخلل وخس',
    descriptionEn: '2 spicy zinger crispy pieces + smoked turkey + cheddar + Taco sauce + pickles & lettuce',
    price: 80,
    costPrice: 44,
    categoryId: 'cat-tacos',
    image: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isPopular: true,
    hasSpicyOption: true,
  },
  {
    id: 'prod-tc9',
    sku: 'TB-TC09',
    barcode: '62230009',
    nameAr: 'تاكو تشيكن سنجل',
    nameEn: 'Single Chicken Taco',
    descriptionAr: '1 قطعة سكالوب دجاج + رومي مدخن + صوص الشيدر + مخلل + صوص تاكو بروست + خس',
    descriptionEn: '1 chicken escalope + smoked turkey + cheddar + pickles + Taco sauce + lettuce',
    price: 80,
    costPrice: 42,
    categoryId: 'cat-tacos',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-tc10',
    sku: 'TB-TC10',
    barcode: '62230010',
    nameAr: 'تاكو تشيكن دبل',
    nameEn: 'Double Chicken Taco',
    descriptionAr: '2 قطعة سكالوب دجاج + رومي مدخن + صوص الشيدر + مخلل + صوص تاكو بروست + خس',
    descriptionEn: '2 chicken escalopes + smoked turkey + cheddar + pickles + Taco sauce + lettuce',
    price: 140,
    costPrice: 76,
    categoryId: 'cat-tacos',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-tc11',
    sku: 'TB-TC11',
    barcode: '62230011',
    nameAr: 'تاكو تشيكن تريبل',
    nameEn: 'Triple Chicken Taco',
    descriptionAr: '3 قطع سكالوب دجاج + رومي مدخن + صوص الشيدر + مخلل + صوص تاكو بروست + خس',
    descriptionEn: '3 chicken escalopes + smoked turkey + cheddar + pickles + Taco sauce + lettuce',
    price: 170,
    costPrice: 92,
    categoryId: 'cat-tacos',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-tc12',
    sku: 'TB-TC12',
    barcode: '62230012',
    nameAr: 'ساندوتش بطاطس',
    nameEn: 'Fries Sandwich',
    descriptionAr: 'بطاطس مقلية مقرمشة + مايونيز + كاتشب في عيش طازج',
    descriptionEn: 'Crispy french fries + mayo + ketchup in a fresh bread bun',
    price: 25,
    costPrice: 10,
    categoryId: 'cat-tacos',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },

  // --- المقبلات والبطاطس ---
  {
    id: 'prod-sd1',
    sku: 'TB-SD01',
    barcode: '62240001',
    nameAr: 'تشيلي تشيز فرايز',
    nameEn: 'Chili Cheese Fries',
    descriptionAr: 'بطاطس محمرة ذهبية مع شلال صوص الشيدر الساخن مع هالبينو حار ولحم مفروم متبل',
    descriptionEn: 'Golden fries + hot melted cheddar cheese + sliced spicy jalapenos + seasoned minced beef',
    price: 60,
    costPrice: 30,
    categoryId: 'cat-sides',
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'prod-sd2',
    sku: 'TB-SD02',
    barcode: '62240002',
    nameAr: 'أرز بسمتي فاخر',
    nameEn: 'Premium Basmati Rice',
    descriptionAr: 'أرز بسمتي أصفر مبهر بالخلطة السرية المميزة لمطعم تاكو بروست',
    descriptionEn: 'Yellow aromatic basmati rice cooked with Taco Broast secret spices',
    price: 25,
    costPrice: 12,
    categoryId: 'cat-sides',
    image: 'https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-sd3',
    sku: 'TB-SD03',
    barcode: '62240003',
    nameAr: 'شيدر استربس',
    nameEn: 'Cheddar Strips',
    descriptionAr: 'أصابع ستربس دجاج مقرمشة مغطاة تماماً بصوص الجبنة الشيدر السائحة',
    descriptionEn: 'Crispy chicken strips fully drenched in creamy warm cheddar cheese sauce',
    price: 60,
    costPrice: 32,
    categoryId: 'cat-sides',
    image: 'https://images.unsplash.com/photo-1562967914-608f82629710?w=600&auto=format&fit=crop&q=80&q=80',
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'prod-sd4',
    sku: 'TB-SD04',
    barcode: '62240004',
    nameAr: 'بطاطس محمرة',
    nameEn: 'French Fries',
    descriptionAr: 'باكت بطاطس مقرمشة ذهبية طازجة',
    descriptionEn: 'Crispy hot golden french fries packet',
    price: 20,
    costPrice: 9,
    categoryId: 'cat-sides',
    image: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-sd5',
    sku: 'TB-SD05',
    barcode: '62240005',
    nameAr: 'كول سلو',
    nameEn: 'Coleslaw Salad',
    descriptionAr: 'سلطة الملفوف والجزر الطازج مع الكريمة الغنية اللذيذة',
    descriptionEn: 'Fresh shredded cabbage and carrot in sweet creamy dressing',
    price: 10,
    costPrice: 4,
    categoryId: 'cat-sides',
    image: 'https://images.unsplash.com/photo-1625944525533-473f1a3d54e7?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-sd6',
    sku: 'TB-SD06',
    barcode: '62240006',
    nameAr: 'ريزو بقطع الدجاج المقرمش',
    nameEn: 'Crispy Chicken Rizo',
    descriptionAr: 'طبق أرز ريزو بالبهارات مع قطع الدجاج الكريسبي وصوص الباربكيو المدخن',
    descriptionEn: 'Flavorful spiced rice bowl topped with crispy chicken pieces & smokey BBQ drizzle',
    price: 60,
    costPrice: 31,
    categoryId: 'cat-sides',
    image: 'https://images.unsplash.com/photo-1516714435131-44d6b64dc6a2?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
    isPopular: true,
  },
  {
    id: 'prod-sd7',
    sku: 'TB-SD07',
    barcode: '62240007',
    nameAr: 'بطاطس جبنة',
    nameEn: 'Cheese Fries',
    descriptionAr: 'بطاطس مقلية مقرمشة مغطاة بصوص الشيدر اللذيذ',
    descriptionEn: 'Crispy french fries generously topped with warm cheddar sauce',
    price: 25,
    costPrice: 12,
    categoryId: 'cat-sides',
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-sd8',
    sku: 'TB-SD08',
    barcode: '62240008',
    nameAr: 'بطاطس جبنة هالبينو',
    nameEn: 'Jalapeno Cheese Fries',
    descriptionAr: 'بطاطس مقلية مع صوص الشيدر الساخن وشرائح هالبينو حار',
    descriptionEn: 'French fries with warm cheddar cheese sauce and spicy jalapeno rings',
    price: 30,
    costPrice: 14,
    categoryId: 'cat-sides',
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-sd9',
    sku: 'TB-SD09',
    barcode: '62240009',
    nameAr: '3 أصابع موتزاريلا ستيكس',
    nameEn: '3 Mozzarella Sticks',
    descriptionAr: '3 أصابع جبنة موتزاريلا مقرمشة ذهبية مع صوص غمس',
    descriptionEn: '3 crispy golden mozzarella cheese sticks with dip',
    price: 30,
    costPrice: 15,
    categoryId: 'cat-sides',
    image: 'https://images.unsplash.com/photo-1531749668029-2db88e4276c7?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-sd10',
    sku: 'TB-SD10',
    barcode: '62240010',
    nameAr: '6 أصابع موتزاريلا ستيكس',
    nameEn: '6 Mozzarella Sticks',
    descriptionAr: '6 أصابع جبنة موتزاريلا مقرمشة غنية وسايحة',
    descriptionEn: '6 crispy golden mozzarella cheese sticks with dip',
    price: 55,
    costPrice: 28,
    categoryId: 'cat-sides',
    image: 'https://images.unsplash.com/photo-1531749668029-2db88e4276c7?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-sd11',
    sku: 'TB-SD11',
    barcode: '62240011',
    nameAr: 'تومية كبير',
    nameEn: 'Large Garlic Dip',
    descriptionAr: 'علبة صوص تومية كريمي حجم كبير',
    descriptionEn: 'Large container of signature creamy garlic sauce',
    price: 10,
    costPrice: 4,
    categoryId: 'cat-sides',
    image: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-sd12',
    sku: 'TB-SD12',
    barcode: '62240012',
    nameAr: 'كيس عيش كيزر طازج',
    nameEn: 'Fresh Bread Bag',
    descriptionAr: 'كيس عيش كيزر ساخن وطري',
    descriptionEn: 'Bag of fresh warm soft buns',
    price: 10,
    costPrice: 4,
    categoryId: 'cat-sides',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },

  // --- صوصات تاكو بروست ---
  {
    id: 'prod-sc1',
    sku: 'TB-SC01',
    barcode: '62250001',
    nameAr: 'صوص تكساس',
    nameEn: 'Texas Sauce',
    descriptionAr: 'صوص تكساس الخاص باللحم المشوي والبروست',
    descriptionEn: 'Signature smoky Texas sauce for burgers and broast',
    price: 15,
    costPrice: 6,
    categoryId: 'cat-sauces',
    image: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-sc2',
    sku: 'TB-SC02',
    barcode: '62250002',
    nameAr: 'مايونيز فاخر',
    nameEn: 'Premium Mayonnaise',
    descriptionAr: 'صوص مايونيز غني وكريمي',
    descriptionEn: 'Rich and creamy premium mayonnaise',
    price: 10,
    costPrice: 4,
    categoryId: 'cat-sauces',
    image: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-sc3',
    sku: 'TB-SC03',
    barcode: '62250003',
    nameAr: 'صوص باربكيو مدخن',
    nameEn: 'Smoked BBQ Sauce',
    descriptionAr: 'صوص باربكيو بنكهة الشواء والتدخين الأمريكية',
    descriptionEn: 'American style rich smokey BBQ dipping sauce',
    price: 12,
    costPrice: 5,
    categoryId: 'cat-sauces',
    image: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-sc4',
    sku: 'TB-SC04',
    barcode: '62250004',
    nameAr: 'صوص تاكو سبايسي',
    nameEn: 'Spicy Taco Sauce',
    descriptionAr: 'صوص تاكو بروست الحار المميز بنكهة التوابل الخاصة',
    descriptionEn: 'Spicy Taco Broast signature pepper sauce',
    price: 15,
    costPrice: 6,
    categoryId: 'cat-sauces',
    image: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-sc5',
    sku: 'TB-SC05',
    barcode: '62250005',
    nameAr: 'كوب صوص شيدر سايح',
    nameEn: 'Melted Cheddar Cup',
    descriptionAr: 'كوب جبنة شيدر سائلة ساخنة للغمس والصب',
    descriptionEn: 'Cup of warm melted cheddar cheese for dipping and pouring',
    price: 20,
    costPrice: 9,
    categoryId: 'cat-sauces',
    image: 'https://images.unsplash.com/photo-1541544741938-0af808871cc0?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },

  // --- المشروبات الغازية والمياه ---
  {
    id: 'prod-dr1',
    sku: 'TB-DR01',
    barcode: '62260001',
    nameAr: 'كولا كانز 330 مل',
    nameEn: 'Cola Can 330ml',
    descriptionAr: 'كولا مثلجة ومنعشة 330 مل',
    descriptionEn: 'Chilled refreshing Cola can 330ml',
    price: 15,
    costPrice: 9,
    categoryId: 'cat-drinks',
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-dr2',
    sku: 'TB-DR02',
    barcode: '62260002',
    nameAr: 'كولا 1.5 لتر عائلي',
    nameEn: 'Cola 1.5L Family Size',
    descriptionAr: 'زجاجة كولا حجم عائلي 1.5 لتر مثلجة',
    descriptionEn: 'Chilled family size Cola bottle 1.5L',
    price: 35,
    costPrice: 22,
    categoryId: 'cat-drinks',
    image: 'https://images.unsplash.com/photo-1554866585-cd94860890b7?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
  {
    id: 'prod-dr3',
    sku: 'TB-DR03',
    barcode: '62260003',
    nameAr: 'مياه معدنية صغير',
    nameEn: 'Small Mineral Water',
    descriptionAr: 'زجاجة مياه معدنية طبيعية نقية 600 مل',
    descriptionEn: 'Pure natural mineral water bottle 600ml',
    price: 8,
    costPrice: 4,
    categoryId: 'cat-drinks',
    image: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=600&auto=format&fit=crop&q=80',
    isAvailable: true,
  },
];

export const initialUsers: User[] = [
  {
    id: 'usr-admin',
    name: 'أحمد الإداري (Super Admin)',
    email: 'admin@tacobroast.com',
    role: 'SUPER_ADMIN',
    phone: '01036130204',
    branch: 'الفرع الرئيسي - شبرا النخلة',
    active: true,
  },
  {
    id: 'usr-manager',
    name: 'محمود المدير (Manager)',
    email: 'manager@tacobroast.com',
    role: 'MANAGER',
    phone: '01011112233',
    branch: 'الفرع الرئيسي - شبرا النخلة',
    active: true,
  },
  {
    id: 'usr-cashier',
    name: 'سارة الكاشير (Jane Doe / Cashier)',
    email: 'cashier@tacobroast.com',
    role: 'CASHIER',
    phone: '01022223344',
    branch: 'Register 04',
    active: true,
  },
  {
    id: 'usr-kitchen',
    name: 'شيف حسام (Kitchen Master)',
    email: 'kitchen@tacobroast.com',
    role: 'KITCHEN',
    phone: '01033334455',
    branch: 'Main Kitchen KDS',
    active: true,
  },
  {
    id: 'usr-delivery',
    name: 'إبراهيم الطيار (Delivery Hero)',
    email: 'delivery@tacobroast.com',
    role: 'DELIVERY',
    phone: '01044445566',
    branch: 'Fleet Delivery',
    active: true,
  },
];

export const initialDeliveryEmployees: DeliveryEmployee[] = [
  {
    id: 'del-1',
    name: 'إبراهيم الطيار',
    phone: '01044445566',
    vehicleType: 'موتوسيكل دايون سريع',
    vehiclePlate: 'ق هـ ج 512',
    isAvailable: true,
    currentLocation: {
      lat: 30.3135,
      lng: 31.4295,
      updatedAt: new Date().toISOString(),
    },
  },
  {
    id: 'del-2',
    name: 'علي حسن السريع',
    phone: '01099887766',
    vehicleType: 'سكوتر بينيلي',
    vehiclePlate: 'س ط ع 894',
    isAvailable: true,
    currentLocation: {
      lat: 30.315,
      lng: 31.431,
      updatedAt: new Date().toISOString(),
    },
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'محمد عبدالله',
    phone: '01099999999',
    address: 'شارع الجمهورية عمارة النور الدور 3',
    location: {
      lat: 30.318,
      lng: 31.435,
    },
    notes: 'يفضل الرن على الجرس بهدوء',
    totalOrders: 4,
    totalSpent: 480,
    createdAt: '2026-08-20T10:00:00.000Z',
    lastOrderAt: '2026-09-02T08:30:00.000Z',
  },
  {
    id: 'cust-2',
    name: 'أميرة سالم',
    phone: '01012345678',
    address: 'ش السنترال بجوار صيدلية الأمل',
    location: {
      lat: 30.314,
      lng: 31.43,
    },
    totalOrders: 2,
    totalSpent: 260,
    createdAt: '2026-08-25T14:15:00.000Z',
    lastOrderAt: '2026-09-01T19:00:00.000Z',
  },
];

export const initialSettings: RestaurantSettings = {
  restaurantNameAr: 'تاكو بروست | Taco Broast',
  restaurantNameEn: 'Taco Broast',
  hotline: '01036130204',
  addressAr: 'ش السنترال بجوار فرن العمده - شبرا النخلة',
  addressEn: 'Central St, Next to Al-Omda Bakery, Shubra El-Nakhla',
  branchLocation: {
    lat: 30.3125,
    lng: 31.4285,
  },
  taxRate: 0.08,
  defaultDeliveryFee: 15,
  currencySymbolAr: 'ج.م',
  currencySymbolEn: 'EGP',
  paperRules: {
    dineInSlips: 1,
    takeAwaySlips: 2,
    deliverySlips: 1,
  },
  autoPrintEnabled: true,
  audioAlertsEnabled: true,
  screenPasswords: {
    pos: '1234',
    kitchen: '2222',
    delivery: '3333',
    admin: '9999',
  },
};

export const initialWhatsAppTemplates: WhatsAppTemplate[] = [
  {
    id: 'wt-1',
    key: 'NEW',
    titleAr: 'استلام الطلب',
    body: 'مرحباً {CUSTOMER_NAME} 🌮 تم استلام طلبك رقم {ORDER_NO} في مطعم تاكو بروست بقيمة {TOTAL} ج.م وجاري المراجعة. شكراً لاختيارك لنا!',
  },
  {
    id: 'wt-2',
    key: 'ACCEPTED',
    titleAr: 'قبول الطلب',
    body: 'عزيزي {CUSTOMER_NAME}، تم قبول طلبك #{ORDER_NO} بنجاح! يتم الآن توجيهه للمطبخ للبدء في التحضير الطازج 🔥',
  },
  {
    id: 'wt-3',
    key: 'PREPARING',
    titleAr: 'جاري التحضير',
    body: 'طلبك #{ORDER_NO} يطهى الآن في المطبخ بأشهى الخلطات الساخنة 🍗 دقائق ويكون جاهز!',
  },
  {
    id: 'wt-4',
    key: 'READY',
    titleAr: 'الطلب جاهز',
    body: 'أهلاً {CUSTOMER_NAME}! طلبك #{ORDER_NO} جاهز الآن في فرع تاكو بروست شبرا النخلة.',
  },
  {
    id: 'wt-5',
    key: 'OUT_FOR_DELIVERY',
    titleAr: 'خرج مع المندوب',
    body: 'طلبك #{ORDER_NO} خرج الآن للتوصيل مع الكابتن {DRIVER_NAME} ({DRIVER_PHONE}) 🛵 يمكنك تتبع موقعه لحظياً عبر الرابط: {TRACK_LINK}',
  },
  {
    id: 'wt-6',
    key: 'DELIVERED',
    titleAr: 'تم التسليم',
    body: 'بالهناء والشفاء! نتمنى أن تنال وجبة تاكو بروست إعجابك 🧡 شاركنا رأيك دائماً عبر 01036130204.',
  },
  {
    id: 'wt-7',
    key: 'THANK_YOU',
    titleAr: 'شكراً لزيارتك',
    body: 'شكراً لطلبك من تاكو بروست! خصم 10% على طلبك القادم عند إدخال كود TACO10 ✨',
  },
];

export const initialInventory: InventoryItem[] = [
  {
    id: 'inv-1',
    nameAr: 'قطع دجاج بلدي طازج متبل',
    nameEn: 'Fresh Seasoned Chicken Pieces',
    sku: 'RAW-CHK-01',
    category: 'لحوم ودواجن',
    currentStock: 140,
    unit: 'قطعة',
    minThreshold: 30,
    costPerUnit: 18,
    supplier: 'مزارع الدواجن البلدي',
  },
  {
    id: 'inv-2',
    nameAr: 'لحم بقري صافي مفروم للشواء',
    nameEn: 'Pure Minced Beef for Grill',
    sku: 'RAW-BEEF-01',
    category: 'لحوم ودواجن',
    currentStock: 45,
    unit: 'كجم',
    minThreshold: 10,
    costPerUnit: 260,
    supplier: 'جزارة البركة',
  },
  {
    id: 'inv-3',
    nameAr: 'بطاطس نصف مقلية ذهبية',
    nameEn: 'Golden Fries Pre-cut',
    sku: 'RAW-FRIES-01',
    category: 'خضروات ومجمدات',
    currentStock: 85,
    unit: 'كجم',
    minThreshold: 20,
    costPerUnit: 35,
  },
  {
    id: 'inv-4',
    nameAr: 'جبنة شيدر سائلة فاخرة',
    nameEn: 'Melted Cheddar Sauce',
    sku: 'RAW-CHED-01',
    category: 'ألبان وجبن',
    currentStock: 30,
    unit: 'لتر',
    minThreshold: 8,
    costPerUnit: 90,
  },
  {
    id: 'inv-5',
    nameAr: 'خبز كيزر طازج سمسم',
    nameEn: 'Sesame Fresh Burger Buns',
    sku: 'BAK-BUN-01',
    category: 'مخبوزات',
    currentStock: 220,
    unit: 'رغيف',
    minThreshold: 50,
    costPerUnit: 3.5,
    supplier: 'فرن العمدة - شبرا النخلة',
  },
  {
    id: 'inv-6',
    nameAr: 'رول ورق حراري 80 مم للطباعة',
    nameEn: 'Thermal Paper Roll 80mm',
    sku: 'SUP-PRN-80',
    category: 'مستلزمات وطباعة',
    currentStock: 28,
    unit: 'بكرة',
    minThreshold: 6,
    costPerUnit: 25,
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp-1',
    category: 'مشتريات خامات',
    amount: 1250,
    description: 'شراء دواجن طازجة وجبن شيدر',
    date: '2026-09-02T07:30:00.000Z',
    createdByName: 'أحمد الإداري',
  },
  {
    id: 'exp-2',
    category: 'فواتير ومرافق',
    amount: 450,
    description: 'شحن غاز للمطابخ والشواية',
    date: '2026-09-01T15:00:00.000Z',
    createdByName: 'محمود المدير',
  },
  {
    id: 'exp-3',
    category: 'نثريات وطباعة',
    amount: 150,
    description: 'كرتونة بكر ورق طباعة فواتير 80مم',
    date: '2026-09-01T11:00:00.000Z',
    createdByName: 'أحمد الإداري',
  },
];

export const initialOrders: Order[] = [
  {
    id: 'ord-8492',
    orderNumber: '#TB-8492',
    orderType: 'DELIVERY',
    status: 'OUT_FOR_DELIVERY',
    customerId: 'cust-1',
    customerName: 'محمد عبدالله',
    customerPhone: '01099999999',
    deliveryAddress: 'شارع الجمهورية عمارة النور الدور 3',
    deliveryLocation: {
      lat: 30.318,
      lng: 31.435,
    },
    deliveryInstructions: 'بجوار صيدلية الدكتور علي، الاتصال عند الوصول',
    driverId: 'del-1',
    driverName: 'إبراهيم الطيار',
    driverPhone: '01044445566',
    driverLocation: {
      lat: 30.3148,
      lng: 31.4312,
      updatedAt: new Date().toISOString(),
    },
    items: [
      {
        productId: 'prod-b2',
        nameAr: 'وجبة 3 قطع',
        nameEn: 'Meal 3 Pcs',
        price: 105,
        quantity: 1,
        spicyChoice: 'SPICY',
        extras: [{ id: 'ex-cheddar', nameAr: 'صوص شيدر إضافي', price: 15 }],
      },
      {
        productId: 'prod-tc1',
        nameAr: 'تاكو كلاسيك',
        nameEn: 'Classic Taco',
        price: 80,
        quantity: 2,
        spicyChoice: 'NORMAL',
      },
      {
        productId: 'prod-dr1',
        nameAr: 'كولا كانز 330 مل',
        nameEn: 'Cola Can 330ml',
        price: 15,
        quantity: 2,
      },
    ],
    subtotal: 295,
    discount: 0,
    deliveryFee: 15,
    tax: 24.8,
    total: 334.8,
    paymentStatus: 'UNPAID',
    paymentMethod: 'CASH',
    cashierName: 'Jane Doe',
    createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    printedCount: 1,
    lastPrintedAt: new Date(Date.now() - 24 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord-8493',
    orderNumber: '#TB-8493',
    orderType: 'TAKE_AWAY',
    status: 'PREPARING',
    customerName: 'سارة خالد',
    customerPhone: '01055556677',
    items: [
      {
        productId: 'prod-br1',
        nameAr: 'تكساس برجر',
        nameEn: 'Texas Burger',
        price: 95,
        quantity: 2,
        extras: [{ id: 'ex-cheddar', nameAr: 'جبنة شيدر إضافية', price: 15 }],
      },
      {
        productId: 'prod-sd1',
        nameAr: 'تشيلي تشيز فرايز',
        nameEn: 'Chili Cheese Fries',
        price: 60,
        quantity: 1,
      },
    ],
    subtotal: 265,
    discount: 15,
    deliveryFee: 0,
    tax: 20,
    total: 270,
    paymentStatus: 'PAID',
    paymentMethod: 'CARD',
    cashierName: 'Jane Doe',
    createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    printedCount: 2,
    lastPrintedAt: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
  },
  {
    id: 'ord-8494',
    orderNumber: '#TB-8494',
    orderType: 'DINE_IN',
    tableNumber: 'الطاولة 4',
    status: 'READY',
    customerName: 'عميل محلي #4',
    customerPhone: '01000000000',
    items: [
      {
        productId: 'prod-b1',
        nameAr: 'وجبة 2 قطع',
        nameEn: 'Meal 2 Pcs',
        price: 75,
        quantity: 1,
        spicyChoice: 'NORMAL',
      },
      {
        productId: 'prod-dr1',
        nameAr: 'كولا كانز 330 مل',
        nameEn: 'Cola Can 330ml',
        price: 15,
        quantity: 1,
      },
    ],
    subtotal: 90,
    discount: 0,
    deliveryFee: 0,
    tax: 7.2,
    total: 97.2,
    paymentStatus: 'PAID',
    paymentMethod: 'CASH',
    cashierName: 'Jane Doe',
    createdAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    printedCount: 1,
    lastPrintedAt: new Date(Date.now() - 17 * 60 * 1000).toISOString(),
  },
];
